# Generated by Django 2.2.6 on 2020-03-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=200, unique=True)),
                ('texto_1', models.TextField(blank=True, null=True)),
                ('texto_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customização',
                'verbose_name_plural': 'Customizações',
            },
        ),
    ]
