# Generated by Django 2.2.6 on 2020-03-23 20:42

import Estabelecimento.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('palavras_chave', models.CharField(max_length=200)),
                ('descrição', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=Estabelecimento.models.upload_path_categoria)),
                ('slug', models.SlugField(blank=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateField(auto_now=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='Estabelecimento.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=2)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=200)),
                ('latitude', models.CharField(blank=True, max_length=9, null=True)),
                ('longitude', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosDivulgacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.CharField(max_length=3000)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dados Divulgação',
                'verbose_name_plural': 'Dados Divulgações',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=5)),
                ('latitude', models.CharField(blank=True, max_length=9, null=True)),
                ('longitude', models.CharField(blank=True, max_length=9, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_cidade', to='Estabelecimento.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='FatoEstabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('CNPJ_estabelecimento', models.CharField(blank=True, max_length=18, null=True)),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('CPF_responsavel', models.CharField(max_length=14)),
                ('telefone_contato_1', models.CharField(max_length=13)),
                ('telefone_contato_2', models.CharField(blank=True, max_length=13, null=True)),
                ('email_contato', models.EmailField(max_length=254)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status_destaque', models.BooleanField(default=False)),
                ('impulsionamento', models.IntegerField(default=0)),
                ('nota', models.IntegerField(default=3)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateField(auto_now=True)),
                ('categoria', models.ManyToManyField(blank=True, related_name='estabelecimentos_categorias', to='Estabelecimento.Categoria')),
                ('dados_divulgacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estabelecimento.DadosDivulgacao')),
                ('endereco_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimento_endereco_comercial', to='Estabelecimento.Endereco')),
                ('endereco_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimento_endereco_fiscal', to='Estabelecimento.Endereco')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='ImagensEstabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=200, unique=True)),
                ('imagem_cartao', models.ImageField(upload_to=Estabelecimento.models.upload_path_cartao)),
                ('imagem_1', models.ImageField(blank=True, null=True, upload_to=Estabelecimento.models.upload_path_imagem_1)),
                ('imagem_2', models.ImageField(blank=True, null=True, upload_to=Estabelecimento.models.upload_path_imagem_2)),
                ('imagem_3', models.ImageField(blank=True, null=True, upload_to=Estabelecimento.models.upload_path_imagem_3)),
                ('imagem_4', models.ImageField(blank=True, null=True, upload_to=Estabelecimento.models.upload_path_imagem_4)),
                ('imagem_5', models.ImageField(blank=True, null=True, upload_to=Estabelecimento.models.upload_path_imagem_5)),
            ],
            options={
                'verbose_name': 'Imagens Estabelecimento',
                'verbose_name_plural': 'Imagens Estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Impulsionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impulsionamento_estabelecimento', to='Estabelecimento.FatoEstabelecimento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impulsionamento_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fatoestabelecimento',
            name='imagens_divulgacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estabelecimento.ImagensEstabelecimento'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('data', models.DateField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_estabelecimento', to='Estabelecimento.FatoEstabelecimento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('IP', 'estabelecimento')},
            },
        ),
    ]
