# Generated by Django 2.2.4 on 2020-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
