# Generated by Django 2.2.4 on 2020-05-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0002_auto_20200413_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='CPF_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='estabelecimentos_categorias', to='Estabelecimento.Categoria'),
        ),
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='telefone_contato_1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
