# Generated by Django 2.2.4 on 2020-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0006_auto_20200507_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
