# Generated by Django 2.2.4 on 2020-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0007_auto_20200507_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosdivulgacao',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
