# Generated by Django 2.2.4 on 2020-05-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0009_auto_20200507_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='dados_divulgacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimento_dados_divulgacao', to='Estabelecimento.DadosDivulgacao'),
        ),
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='endereco_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimento_endereco_comercial', to='Estabelecimento.Endereco'),
        ),
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='endereco_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimento_endereco_fiscal', to='Estabelecimento.Endereco'),
        ),
    ]
