# Generated by Django 2.2.4 on 2020-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0012_auto_20200507_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatoestabelecimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
