# Generated by Django 2.2.4 on 2020-05-15 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0013_fatoestabelecimento_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impulsionamento',
            name='data',
        ),
        migrations.AddField(
            model_name='impulsionamento',
            name='IP',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impulsionamento',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
