# Generated by Django 2.2.4 on 2020-05-15 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0014_auto_20200515_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='impulsionamento',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
