# Generated by Django 2.2.4 on 2020-09-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0016_fatoestabelecimento_alcance_nacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatoestabelecimento',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=3),
        ),
    ]
