# Generated by Django 2.2.4 on 2020-09-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0017_auto_20200912_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impulsionamento',
            name='IP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
