# Generated by Django 2.2.4 on 2020-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0018_auto_20200913_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatoestabelecimento',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
