# Generated by Django 2.2.4 on 2020-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estabelecimento', '0019_fatoestabelecimento_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='palavras_chave',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
